const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },
  destination: {
    type: String,
    required: true,
  },
  budget: {
    type: String,
    required: true,
  },
  duration: {
    type: Number,
    required: true,
  },
  travellers: {
    type: Number,
    required: true,
  },
  itineraryData: {
    type: Object, // Stores the exact JSON generated by AI
    required: true,
  }
}, {
  timestamps: true,
});

const Trip = mongoose.model('Trip', tripSchema);
module.exports = Trip;
